# Generated by Django 6.0.7 on 2026-08-01 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен начинаться с 8 и содержать 11 цифр",
                        regex="^8\\d{10}$",
                    )
                ],
            ),
        ),
    ]
